CREATE SCHEMA POSTAJE;

 

CREATE TABLE POSTAJE.DRZAVA (

  ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,

  NAZIV VARCHAR(50) NOT NULL,

  POVRSINA DOUBLE NOT NULL,

  PRIMARY KEY (ID)

);

 

INSERT INTO POSTAJE.DRZAVA (NAZIV, POVRSINA) VALUES

  ('Hrvatska', 56594),

  ('Slovenija', 20273);

 

CREATE TABLE POSTAJE.ZUPANIJA (

  ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,

  NAZIV VARCHAR(50) NOT NULL,

  DRZAVA_ID INT NOT NULL,

  PRIMARY KEY (ID),

  FOREIGN KEY(DRZAVA_ID) REFERENCES POSTAJE.DRZAVA(ID)

);

 

INSERT INTO POSTAJE.ZUPANIJA (NAZIV, DRZAVA_ID) VALUES

  ('Grad Zagreb', 1),

  ('Lièko-senjska županija', 1),

  ('Brodsko-posavska županija', 1),

  ('Nova Gorica', 2),

  ('Novo Mesto', 2);

 

CREATE TABLE POSTAJE.MJESTO (

  ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,

  NAZIV VARCHAR(50) NOT NULL,

  VRSTA VARCHAR(50) NOT NULL,

  ZUPANIJA_ID INT NOT NULL,

  PRIMARY KEY (ID),

  FOREIGN KEY(ZUPANIJA_ID) REFERENCES POSTAJE.ZUPANIJA(ID)

);

 

INSERT INTO POSTAJE.MJESTO (NAZIV, VRSTA, ZUPANIJA_ID) VALUES

  ('Grad Zagreb', 'GRAD', 1),

  ('Zavižan', 'OSTALO', 2),

  ('Otoèac', 'GRAD', 2),

  ('Slavonski Brod', 'GRAD', 3);

 

CREATE TABLE POSTAJE.MJERNA_POSTAJA (

  ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,

  NAZIV VARCHAR(50) NOT NULL,

  MJESTO_ID INT NOT NULL,

  LAT DECIMAL(10, 8) NOT NULL,

  LNG DECIMAL(11, 8) NOT NULL,

  PRIMARY KEY (ID),

  FOREIGN KEY(MJESTO_ID) REFERENCES POSTAJE.MJESTO(ID)

);

 

INSERT INTO POSTAJE.MJERNA_POSTAJA (NAZIV, MJESTO_ID, LAT, LNG) VALUES

  ('Maksimir', 1, 45.818557, 16.016666),

  ('Zavižan', 1, 44.800000, 14.966667);

 

 

CREATE TABLE POSTAJE.SENZOR (

  ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,

  MJERNA_JEDINICA VARCHAR(10) NOT NULL,

  PRECIZNOST DOUBLE NOT NULL,

  VRIJEDNOST DECIMAL(7, 2),

  RAD_SENZORA VARCHAR(10),

  MJERNA_POSTAJA_ID INT NOT NULL,

  PRIMARY KEY (ID),

  FOREIGN KEY(MJERNA_POSTAJA_ID) REFERENCES POSTAJE.MJERNA_POSTAJA(ID)

);

 

INSERT INTO POSTAJE.SENZOR (MJERNA_JEDINICA, PRECIZNOST, VRIJEDNOST, RAD_SENZORA, MJERNA_POSTAJA_ID) VALUES

  ('g', 30, 20, 'STREAMING', 1),

  ('kg', 5, 1, 'PING', 1);